### ISSUE TITLE
rpi-5.4.y kernels?

### ISSUE THREAD

**Issue by rfinnie** [sakaki-/bcm2711-kernel#2]
Any plans to start doing this (and -bis) for the rpi-5.4.y LTS branch?  bcm2711_defconfig seems to be stable at this point (or at least no issues on the one I compiled a few days ago).  Thanks for doing these kernels BTW!

**Comment by TwinUsers** [comment]
Wouldn’t 5.4.x be considered as testing only? I think it would be best to stay on the 4.19.x branch

It’s stable and unlikely to get a kernel dump

**Comment by rfinnie** [comment]
5.4 is the latest upstream (kernel.org) LTS and historically, Raspbian has been using the LTS bases for their published kernels.  4.19 is currently the latest published Raspbian kernel and is the previous kernel.org LTS, so Raspbian will likely be moving to 5.4 relatively soon.

Not suggesting this project switch from 4.19 to 5.4, but was curious if 5.4 releases could be added in addition.  FWIW, I've published a script I use to compile 5.4 kernels: https://github.com/rfinnie/rpi-kernel-build

**Comment by TwinUsers** [comment]
I’m going to attempt a 5.4.x. Kernel later today. Have you got any raspberry pi’s running it out of curiosity 👍

**Comment by rfinnie** [comment]
Works fine for RPi4:

```
ryan@zapp:~$ uname -a
Linux zapp 5.4.24-g531d3d5c8982-20200313-p4-bis #1 SMP PREEMPT Tue Mar 17 03:20:11 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ryan@zapp:~$ sudo lshw | head
zapp                        
    description: Computer
    product: Raspberry Pi 4 Model B Rev 1.1
    serial: 1000000056b545a0
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled
```

Presumably rpi-5.4.y is also usable on 3/3+, but my script only supports bcm2711.

**Comment by TwinUsers** [comment]
A few commits behind the 4.19 branch though. Is it stable enough to run on a production server?

**Comment by sakaki-** [comment]
I'll be switching over to the `rpi-5.4.y` branch in the next couple of weeks. Apologies for not replying earlier, been a busy time ><

**Comment by sakaki-** [comment]
First 5.4 kernels are out...

**Comment by sakaki-** [comment]
Closing this now. Preliminary testing of the 5.4 kernels on the RPi3/4 indicates they work acceptably. Please re-open if any issues.
Thanks! sakaki
